### ISSUE TITLE
question ?

### ISSUE THREAD

**Issue by smolleyes** [audio-lab/analyser#1]
hi

possible to link all your projects to an existing html player ? (mediaelement.js)

for exemple catch the audio output of this player to render it somewhere but let the player read/play the file...

thanks

**Comment by dy** [comment]
Hi!
Do I get you right that you want to intercept audio from a _MediaElement_ and direct it to, for example, [audio-biquad](https://github.com/audio-lab/audio-biquad)?
Not yet. But there are plans for that.

**Comment by smolleyes** [comment]
that s it yep :) to biquad or spectrum or even chain them all  :)

ok cool !
